SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS recordanswer;
DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS themes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS questions;
SET FOREIGN_KEY_CHECKS = 1;